providers:
  docker: {}
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  web:
    address: ":80"

ping: {}
accessLog: {}
api:
  insecure: true

experimental:
  localPlugins:
    rpp:
      moduleName: github.com/SwanHubX/req-preprocess
